# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-04 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180903_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='abcd'),
        ),
    ]
