# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-26 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='carts',
            new_name='cart',
        ),
    ]
